name: Docker test build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build_php56:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Test Docker build
      run: docker build --tag php5.6-fpm:$GITHUB_SHA --file ./5.6-fpm/Dockerfile ./5.6-fpm
