name: Test build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build_php56:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP5.6-fpm test build
        run: make test-build-php56-fpm

  build_php56_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP5.6-fpm-dev test build
        run: make test-build-php56-fpm-dev

  build_php74_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP7.4-fpm-dev test build
        run: make php74-dev-testbuild
