name: Docker test build

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build_php56:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Docker build
        run: make test-build-php56-fpm
