name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build/Publish PHP5.6-fpm
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: albenikd/php
        dockerfile: '5.6-fpm/Dockerfile'
        context: '5.6-fpm'
        tags: '5.6-fpm'
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
