name: Docker Hub Publish

on:
  pull_request:
    types: [closed]

jobs:
  publish_php56:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: albenikd/php
          dockerfile: "5.6-fpm/Dockerfile"
          context: "5.6-fpm"
          tags: "5.6-fpm"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish_php56_dev:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: albenikd/php
          dockerfile: "5.6-fpm-dev/Dockerfile"
          context: "5.6-fpm-dev"
          tags: "5.6-fpm-dev"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish_php74_dev:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Publish to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: albenikd/php
          dockerfile: "7.4-dev/Dockerfile"
          context: "7.4-dev"
          tags: "5.7-dev"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
